name: publish

on:
  release:
    types: [published]

env:
  REGISTRY: "ghcr.io"
  GHCR_ORG: "XpiritBV"
  CONTAINER_NAME: "notes-app"
  CONTAINER_TAG: "latest"

jobs:
  publish-container:
    name: Publish Notes App Container to GHCR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GHCR Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: downcase REPO
        run: |
          echo "REPO=${GHCR_ORG,,}" >>${GITHUB_ENV}
      - name: Build and publish image
        run: |
          docker build . --tag ${{ env.REGISTRY }}/${{ env.REPO }}/${{ env.CONTAINER_NAME }}:${{ env.CONTAINER_TAG }}
          docker push ghcr.io/${{ env.REPO }}/${{ env.CONTAINER_NAME }}:${{ env.CONTAINER_TAG }}